/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Patient model module.
 * @module model/Patient
 * @version 1.0.0
 */
class Patient {
    /**
     * Constructs a new <code>Patient</code>.
     * @alias module:model/Patient
     * @param pname {String} 
     * @param lname {String} 
     * @param amka {String} 
     * @param mphone {String} 
     */
    constructor(pname, lname, amka, mphone) { 
        
        Patient.initialize(this, pname, lname, amka, mphone);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pname, lname, amka, mphone) { 
        obj['pname'] = pname;
        obj['lname'] = lname;
        obj['amka'] = amka;
        obj['mphone'] = mphone;
    }

    /**
     * Constructs a <code>Patient</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Patient} obj Optional instance to populate.
     * @return {module:model/Patient} The populated <code>Patient</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Patient();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('pname')) {
                obj['pname'] = ApiClient.convertToType(data['pname'], 'String');
            }
            if (data.hasOwnProperty('lname')) {
                obj['lname'] = ApiClient.convertToType(data['lname'], 'String');
            }
            if (data.hasOwnProperty('amka')) {
                obj['amka'] = ApiClient.convertToType(data['amka'], 'String');
            }
            if (data.hasOwnProperty('mphone')) {
                obj['mphone'] = ApiClient.convertToType(data['mphone'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Patient.prototype['_id'] = undefined;

/**
 * @member {String} pname
 */
Patient.prototype['pname'] = undefined;

/**
 * @member {String} lname
 */
Patient.prototype['lname'] = undefined;

/**
 * @member {String} amka
 */
Patient.prototype['amka'] = undefined;

/**
 * @member {String} mphone
 */
Patient.prototype['mphone'] = undefined;






export default Patient;

